##
## Test Suites
##

    modified.files.includes[relevant][ant-bnd-rule]=**

    relevant.rule.names=\
        ant-bnd-rule

    test.batch.names[relevant][ant-bnd-rule]=\
        modules-integration-mysql57-jdk8,\
        modules-unit-jdk8

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57-jdk8][relevant][ant-bnd-rule]=\
        sdk/ant-bnd/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit-jdk8][relevant][ant-bnd-rule]=\
        sdk/ant-bnd/**/*Test.java

##
## Testray
##

    testray.main.component.name=Dev Tools