##
## Relevant
##

    test.batch.run.property.query[functional-upgrade*-tomcat*-mysql*-jdk8][relevant]=\
        (testray.main.component.name == "URL Redirections") AND \
        (testray.main.component.name == "Upgrades WEM")

##
## Testray
##

    testray.main.component.name=Redirect