#
# LXC
#

com.liferay.lxc.dxp.domains=localhost:8080
com.liferay.lxc.dxp.mainDomain=localhost:8080
com.liferay.lxc.dxp.server.protocol=http

#
# OAuth
#

liferay.oauth.application.external.reference.codes=liferay-partner-etc-spring-boot-oauth-application-headless-server
liferay-partner-etc-spring-boot-oauth-application-headless-server.oauth2.headless.server.client.secret=myfancypassword
liferay.oauth.urls.excludes=/ready

#
# Spring Boot
#

server.port=58081

#
# RabbitMQ
#

spring.rabbitmq.listener.simple.acknowledge-mode=manual
spring.rabbitmq.listener.simple.default-requeue-rejected=false
spring.rabbitmq.requested-heartbeat=60
spring.rabbitmq.template.default-receive-queue=
spring.rabbitmq.host=
spring.rabbitmq.password=
spring.rabbitmq.port=
spring.rabbitmq.ssl.enabled=
spring.rabbitmq.username=