#
# OAuth
#

liferay.oauth.application.external.reference.codes=\
    external-liferay,\
    liferay-sample-etc-cron-oauth-application-headless-server

#
# Other
#

liferay.sample.etc.spring.boot.uri=http://localhost:58081