#
# This is a generated file.
#

api.version=v1.0
batch.engine.entity.class.name=com.liferay.headless.object.dto.v1_0.Collaborator
batch.engine.task.item.delegate=true
batch.planner.export.enabled=true
batch.planner.import.enabled=false
entity.class.name=com.liferay.headless.object.dto.v1_0.Collaborator
osgi.jaxrs.application.select=(osgi.jaxrs.name=Liferay.Headless.Object)
osgi.jaxrs.resource=true