##
## Modules
##

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57-jdk8][relevant][asset-browser-web-rule]=\
        **/asset-test/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit-jdk8][relevant][asset-browser-web-rule]=\
        **/asset-test/**/*Test.java

##
## Test Suites
##

    modified.files.includes[relevant][asset-browser-web-rule]=**

    relevant.rule.names=\
        asset-browser-web-rule

    test.batch.names[relevant][asset-browser-web-rule]=\
        modules-integration-mysql57-jdk8,\
        modules-unit-jdk8