#
# LXC
#

com.liferay.lxc.dxp.domains=localhost:8080
com.liferay.lxc.dxp.mainDomain=localhost:8080
com.liferay.lxc.dxp.server.protocol=http

com.liferay.lxc.koroneiki.auth.token=
com.liferay.lxc.koroneiki.auth.url=
com.liferay.lxc.provisioning.auth.client.id=
com.liferay.lxc.provisioning.auth.client.secret=
com.liferay.lxc.provisioning.auth.url=

#
# OAuth
#

liferay.oauth.application.external.reference.codes=liferay-marketplace-etc-spring-boot-oauth-application-user-agent
liferay.oauth.urls.excludes=/ready,/provisioning/license-keys/*/download

#
# Spring Boot
#

server.port=58081