##
## Test Suites
##

    modified.files.includes[relevant][sharepoint-rest-rule]=**

    relevant.rule.names=\
        sharepoint-rest-rule

    test.batch.names[relevant][sharepoint-rest-rule]=\
        functional-tomcat90-mysql57-jdk8

    #
    # Portal Hotfix Release
    #

    test.batch.run.property.query[functional-bundle-tomcat-mysql57-jdk8][test-portal-hotfix-release]=\
        ${test.batch.run.property.query[functional-tomcat*-mysql*-jdk8][relevant][sharepoint-rest-rule]}

    #
    # Relevant
    #

    test.batch.run.property.query[functional-tomcat*-mysql*-jdk8][relevant][sharepoint-rest-rule]=\
        (osgi.modules.includes ~ "sharepoint-rest") AND \
        (portal.acceptance == true)

##
## Testray
##

    testray.main.component.name=Sharepoint