##
## Test Suites
##

    modified.files.excludes[relevant][frontend-js-rule]=frontend-js-web/src/main/resources/META-INF/resources/liferay/util/cookie/*

    modified.files.includes[relevant][frontend-js-rule]=**

    relevant.rule.names=\
        frontend-js-rule

    test.batch.names[relevant][frontend-js-rule]=\
        functional-tomcat90-mysql57-jdk8,\
        modules-integration-mysql57-jdk8,\
        modules-unit-jdk8

    #
    # Portal Hotfix Release
    #

    test.batch.run.property.query[functional-bundle-tomcat-mysql57-jdk8][test-portal-hotfix-release]=\
        ${test.batch.run.property.query[functional-tomcat*-mysql*-jdk8][relevant][frontend-js-rule]}

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57-jdk8][relevant][frontend-js-rule]=\
        apps/frontend-js/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit-jdk8][relevant][frontend-js-rule]=\
        apps/frontend-js/**/*Test.java

    test.batch.run.property.query[functional-tomcat*-mysql*-jdk8][relevant][frontend-js-rule]=\
        (\
            (environment.acceptance == true) OR \
            (testray.component.names ~ "AUI")\
        ) AND \
        (\
            (portal.acceptance == true) AND \
            (portal.upstream == true)\
        ) AND \
        (\
            (app.server.types == null) OR \
            (app.server.types ~ "tomcat")\
        ) AND \
        (\
            (database.types == null) OR \
            (database.types ~ "mysql")\
        ) AND \
        (\
            (operating.system.types == null) OR \
            (operating.system.types ~ "centos")\
        )

##
## Testray
##

    testray.main.component.name=User Interface