#
# LXC
#

com.liferay.lxc.dxp.domains=localhost:8080
com.liferay.lxc.dxp.mainDomain=localhost:8080
com.liferay.lxc.dxp.server.protocol=http

#
# OAuth
#

liferay.oauth.application.external.reference.codes=liferay-sample-commerce-checkout-step-oauth-application-user-agent

#
# List All Resource Endpoints That Should Be Accessible Without Authentication
#
# When Serving Static Resources Make Sure to Include All Files by Their Path
#

liferay.oauth.urls.excludes=/ready,/index.js

#
# Spring Boot
#

server.port=58081

spring.web.resources.static-locations=file:/static/