##
## Modules
##

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57-jdk8][relevant][asset-categories-admin-web-rule]=\
        **/asset-categories-test/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit-jdk8][relevant][asset-categories-admin-web-rule]=\
        **/asset-categories-test/**/*Test.java

##
## Test Suites
##

    modified.files.includes[relevant][asset-categories-admin-web-rule]=**

    relevant.rule.names=\
        asset-categories-admin-web-rule

    test.batch.names[relevant][asset-categories-admin-web-rule]=\
        modules-integration-mysql57-jdk8,\
        modules-unit-jdk8

##
## Testray
##

    testray.main.component.name=Categories