##
## Test Batch
##

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[relevant]=\
        apps/user/**/*Test.java

##
## Testray
##

    testray.main.component.name=Users and Organizations