##
## Relevant
##

    playwright.test.project[playwright-js-tomcat90-mysql57-jdk8][relevant][wiki-web-rule]=wiki-web

    test.batch.run.property.query[functional-upgrade*-tomcat*-mysql*-jdk8][relevant][wiki-web-rule]=\
        (testray.component.names == "Wiki") AND \
        (testray.main.component.name == "Upgrades Content Management")

##
## Test Suites
##

    modified.files.includes[relevant][wiki-web-rule]=**

    relevant.rule.names=\
        wiki-web-rule

    test.batch.names[relevant][wiki-web-rule]=\
        functional-upgrade-tomcat90-mysql57-jdk8,\
        playwright-js-tomcat90-mysql57-jdk8

##
## Testray
##

    testray.main.component.name=Wiki