##
## Test Suites
##

    modified.files.includes[relevant][akismet-rule]=**

    relevant.rule.names=\
        akismet-rule

    test.batch.names[relevant][akismet-rule]=\
        functional-tomcat90-mysql57-jdk8

    #
    # Portal Hotfix Release
    #

    test.batch.run.property.query[functional-bundle-tomcat-mysql57-jdk8][test-portal-hotfix-release]=\
        ${test.batch.run.property.query[functional-tomcat*-mysql*-jdk8][relevant][akismet-rule]}

    #
    # Relevant
    #

    test.batch.run.property.query[functional-tomcat*-mysql*-jdk8][relevant][akismet-rule]=\
        (testray.main.component.name ~ "Akismet")

##
## Testray
##

    testray.main.component.name=Akismet