#
# Application
#

liferay_customer_gcs_bucket_name=${LIFERAY_CUSTOMER_GCS_BUCKET_NAME}
liferay_customer_gcs_service_account_key=${LIFERAY_CUSTOMER_GCS_SERVICE_ACCOUNT_KEY}
liferay_osb_spring_boot_client_zendesk_api_email_address=${LIFERAY_OSB_SPRING_BOOT_CLIENT_ZENDESK_API_EMAIL_ADDRESS}
liferay_osb_spring_boot_client_zendesk_api_token=${LIFERAY_OSB_SPRING_BOOT_CLIENT_ZENDESK_API_TOKEN}
liferay_osb_spring_boot_client_zendesk_url=${LIFERAY_OSB_SPRING_BOOT_CLIENT_ZENDESK_URL}

#
# LXC
#

com.liferay.lxc.dxp.domains=localhost:8080
com.liferay.lxc.dxp.mainDomain=localhost:8080
com.liferay.lxc.dxp.server.protocol=http

#
# OAuth
#

liferay.oauth.application.external.reference.codes=\
    liferay-customer-etc-spring-boot-oauth-application-headless-server,\
    liferay-customer-etc-spring-boot-oauth-application-user-agent

liferay.oauth.urls.excludes=/ready

#
# Spring Boot
#

server.port=58081