##
## Test Suites
##

    modified.files.includes[relevant][site-navigation-rule]=**

    relevant.rule.names=\
        site-navigation-rule

    test.batch.names[relevant][site-navigation-rule]=\
        functional-tomcat90-mysql57-jdk8,\
        modules-integration-mysql57-jdk8,\
        modules-unit-jdk8

    #
    # Portal Hotfix Release
    #

    test.batch.run.property.query[functional-bundle-tomcat-mysql57-jdk8][test-portal-hotfix-release]=\
        ${test.batch.run.property.query[functional-tomcat*-mysql*-jdk8][relevant][site-navigation-rule]}

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57-jdk8][relevant][site-navigation-rule]=\
        apps/site-navigation/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit-jdk8][relevant][site-navigation-rule]=\
        apps/site-navigation/**/*Test.java

    test.batch.run.property.query[functional-tomcat*-mysql*-jdk8][relevant][site-navigation-rule]=\
        (portal.acceptance == true) AND \
        (\
            (testray.main.component.name ~ "Breadcrumb Widget") OR \
            (testray.main.component.name ~ "Localization") OR \
            (testray.main.component.name ~ "Navigation Menus") OR \
            (testray.main.component.name ~ "Sitemap Protocol")\
        )

##
## Testray
##

    testray.main.component.name=Navigation Menus