##
## Test Suites
##

    modified.files.includes[relevant][change-tracking-rule]=**

    relevant.rule.names=\
        change-tracking-rule

    test.batch.names[relevant][change-tracking-rule]=\
        functional-tomcat90-mysql57-jdk8,\
        functional-upgrade-tomcat90-mysql57-jdk8,\
        modules-integration-mysql57-jdk8,\
        modules-unit-jdk8

    modules.includes.required.test.batch.class.names.includes[modules-integration-*-jdk8][relevant][change-tracking-rule]=\
        **/portal-search-test/**/IndexerClausesChangeTrackingTest.java,\
        **/src/testIntegration/**/change/tracking/**/*Test.java,\
        apps/change-tracking/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit-jdk8][relevant][change-tracking-rule]=\
        **/change/tracking/**/*Test.java,\
        apps/change-tracking/**/*Test.java

    #
    # Portal Hotfix Release
    #

    test.batch.run.property.query[functional-bundle-tomcat-mysql57-jdk8][test-portal-hotfix-release]=\
        ${test.batch.run.property.query[functional-tomcat*-mysql*-jdk8][relevant][change-tracking-rule]}

    #
    # Relevant
    #

    test.batch.run.property.query[functional-tomcat*-mysql*-jdk8][relevant][change-tracking-rule]=\
        (portal.acceptance == true) AND \
        (testray.main.component.name ~ "Publications")

    test.batch.run.property.query[functional-upgrade*-tomcat*-mysql*-jdk8][relevant][change-tracking-rule]=\
        (portal.acceptance == true) AND \
        (testray.main.component.name ~ "Upgrades Publications")

##
## Testray
##

    testray.main.component.name=Publications