##
## Test Suites
##

    modified.files.includes[relevant][site-navigation-breadcrumb-web-rule]=**

    relevant.rule.names=\
        site-navigation-breadcrumb-web-rule

    test.batch.names[relevant][site-navigation-breadcrumb-web-rule]=\
        playwright-js-tomcat90-mysql57

    #
    # Relevant
    #

    playwright.test.project[playwright-js-tomcat90-mysql57][relevant][site-navigation-breadcrumb-web-rule]=site-navigation-breadcrumb-web

##
## Testray
##

    testray.main.component.name=Breadcrumb Widget