##
## Test Suites
##

    modified.files.includes[relevant][portal-search-tuning-rule]=**

    relevant.rule.names=\
        portal-search-tuning-rule

    test.batch.names[relevant][portal-search-tuning-rule]=\
        functional-tomcat90-mysql57-jdk8,\
        functional-upgrade-tomcat90-mysql57-jdk8

    #
    # Portal Hotfix Release
    #

    test.batch.run.property.query[functional-bundle-tomcat-mysql57-jdk8][test-portal-hotfix-release]=\
        ${test.batch.run.property.query[functional-tomcat*-mysql*-jdk8][relevant][portal-search-tuning-rule]}

    #
    # Relevant
    #

    test.batch.run.property.query[functional-tomcat*-mysql*-jdk8][relevant][portal-search-tuning-rule]=\
        (portal.acceptance == true) AND \
        (portal.suite.search.engine ~ "elasticsearch7")

    test.batch.run.property.query[functional-upgrade-tomcat*-mysql*-jdk8][relevant][portal-search-tuning-rule]=\
        (portal.suite.search.engine ~ "elasticsearch7") AND \
        (testray.main.component.name ~ "Upgrades Search")

##
## Testray
##

    testray.main.component.name=Elasticsearch Impl