##
## Playwright
##

    playwright.test.project[playwright-js-tomcat90-mysql57-jdk8][relevant]=configuration-admin-web

##
## Test Batch
##

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[relevant]=\
        apps/configuration-admin/**/*Test.java

##
## Testray
##

    testray.main.component.name=System Settings