##
## Test Suites
##

    modified.files.includes[relevant][mail-rule]=**

    relevant.rule.names=\
        mail-rule

    test.batch.names[relevant][mail-rule]=\
        modules-integration-mysql57-jdk8,\
        modules-unit-jdk8

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57-jdk8][relevant][mail-rule]=\
        apps/mail/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit-jdk8][relevant][mail-rule]=\
        apps/mail/**/*Test.java

##
## Testray
##

    testray.main.component.name=Portal Services