##
## Relevant
##

    modules.includes.required.test.batch.class.names.includes[relevant]=\
        apps/document-library-google-docs/**/*Test.java

    test.batch.run.property.query[functional-upgrade*-tomcat*-mysql*-jdk8][relevant]=\
        (testray.component.names == "Online Editing") AND \
        (testray.main.component.name == "Upgrades Content Management")

##
## Testray
##

    testray.main.component.name=Online Editing