apiDir: "../learn-rest-api/src/main/java"
apiPackagePath: "com.liferay.learn.rest"
application:
    baseURI: "/learn"
    className: "LearnRESTApplication"
    name: "Liferay.Learn.REST"
author: "Thiago Buarque"
clientDir: "../learn-rest-client/src/main/java"
compatibilityVersion: 6
forcePredictableOperationId: true
generateGraphQL: false
testDir: "../learn-rest-test/src/testIntegration/java"