##
## Modules
##

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57-jdk8][relevant][asset-category-property-service-rule]=\
        **/asset-category-property-test/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit-jdk8][relevant][asset-category-property-service-rule]=\
        **/asset-category-property-test/**/*Test.java

##
## Test Suites
##

    modified.files.includes[relevant][asset-category-property-service-rule]=**

    relevant.rule.names=\
        asset-category-property-service-rule

    test.batch.names[relevant][asset-category-property-service-rule]=\
        modules-integration-mysql57-jdk8,\
        modules-unit-jdk8

##
## Testray
##

    testray.main.component.name=Categories