##
## Modules
##

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57-jdk8][relevant][questions-rule]=\
        apps/message-boards/**/*Test.java,\
        apps/questions/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit-jdk8][relevant][questions-rule]=\
        apps/message-boards/**/*Test.java,\
        apps/questions/**/*Test.java

    #
    # Portal Hotfix Release
    #

    test.batch.run.property.query[functional-bundle-tomcat-mysql57-jdk8][test-portal-hotfix-release]=\
        ${test.batch.run.property.query[functional-tomcat*-mysql*-jdk8][relevant][questions-rule]}

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[relevant][questions-rule]=\
        apps/questions/**/*Test.java

    test.batch.run.property.query[functional-tomcat*-mysql*-jdk8][relevant][questions-rule]=\
        (portal.acceptance == true) AND \
        (testray.main.component.name ~ "Questions")

##
## Test Suites
##

    modified.files.includes[relevant][questions-rule]=**

    relevant.rule.names=\
        questions-rule

    test.batch.names[relevant][questions-rule]=\
        functional-tomcat90-mysql57-jdk8,\
        modules-integration-mysql57-jdk8,\
        modules-unit-jdk8

##
## Testray
##

    testray.main.component.name=Questions