/**
 * SPDX-FileCopyrightText: (c) 2000 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

import {expect, mergeTests} from '@playwright/test';

import {getRandomInt} from '../../../../../../utils/getRandomInt';
import {partnerPagesTest} from '../../../fixtures/partnerPagesTest';
import {mdfRequestMock} from '../../../mocks/mdfMock';
import {customFormatDate, getDateCustomFormat} from '../../../utils/date';

export const test = mergeTests(partnerPagesTest);

test.describe('MDF Request List', () => {
	let mdfRequest;
	let partnerAccount;
	let userAccount;

	test.beforeEach(
		async ({mdfRequestListPage, partnerHelper, partnerSite}) => {
			partnerAccount =
				await partnerHelper.apiHelpers.headlessAdminUser.postAccount({
					name: 'Partner Account' + getRandomInt(),
					type: 'business',
				});
			userAccount =
				await partnerHelper.apiHelpers.headlessAdminUser.getUserAccountByEmailAddress(
					'test@liferay.com'
				);

			const rolesResponse =
				await partnerHelper.apiHelpers.headlessAdminUser.getAccountRoles(
					partnerAccount.id
				);

			const role = rolesResponse?.items?.filter(
				(role) => role.name === '[Account] Partner Manager (PM)'
			);

			await partnerHelper.apiHelpers.headlessAdminUser.assignUserToAccountRole(
				partnerAccount.id,
				role[0].id,
				userAccount.id
			);

			mdfRequest = await partnerHelper.createMDFRequest({
				data: mdfRequestMock,
			});

			await mdfRequestListPage.goto(partnerSite.friendlyUrlPath);
		}
	);

	test.afterEach(async ({partnerHelper}) => {
		await partnerHelper.apiHelpers.delete(
			`/o/c/mdfrequests/${mdfRequest.id}`
		);
		await partnerHelper.apiHelpers.headlessAdminUser.deleteAccount(
			partnerAccount.id
		);
		await partnerHelper.apiHelpers.headlessAdminUser.deleteAccount(
			userAccount.id
		);
	});

	test('Open MDF Request List', async ({page}) => {
		const heading = await page.getByRole('heading', {
			name: 'MDF Requests',
		});

		expect(heading).toBeTruthy();
	});

	test('Display MDF Resquest List', async ({mdfRequestListPage}) => {
		const autoGenerateData =
			await mdfRequestListPage.getGeneratedDataFromRequest(
				mdfRequest.overallCampaignName
			);
		const campaignName = await mdfRequestListPage.getCampaignName();
		const formatEndDate = getDateCustomFormat(
			mdfRequest.maxDateActivity,
			customFormatDate.SHORT_MONTH
		);
		const formatStartDate = getDateCustomFormat(
			mdfRequest.minDateActivity,
			customFormatDate.SHORT_MONTH
		);

		const endActPeriod =
			await mdfRequestListPage.getEndActPeriod(formatEndDate);
		const partnerName = await mdfRequestListPage.getPartnerName(
			mdfRequest.companyName
		);
		const requested = await mdfRequestListPage.getRequested(
			mdfRequest.totalMDFRequestAmount
		);
		const startActPeriod =
			await mdfRequestListPage.getStartActPeriod(formatStartDate);

		await expect(campaignName).toBeVisible();

		await expect(endActPeriod).toBeVisible();
		await expect(partnerName).toBeVisible();
		await expect(requested).toBeTruthy();
		await expect(autoGenerateData.requestId).toBeTruthy();
		await expect(startActPeriod).toBeVisible();
		await expect(autoGenerateData.status).toBeTruthy();
		await expect(autoGenerateData.submitDate).toBeTruthy();
	});

	test('Filter data by Activity Period', async ({
		mdfRequestListPage,
		page,
	}) => {
		const formatEndDate = getDateCustomFormat(
			mdfRequest.maxDateActivity,
			customFormatDate.SHORT_MONTH
		);
		const formatStartDate = getDateCustomFormat(
			mdfRequest.minDateActivity,
			customFormatDate.SHORT_MONTH
		);
		const endActPeriod =
			await mdfRequestListPage.getEndActPeriod(formatEndDate);
		const startActPeriod =
			await mdfRequestListPage.getStartActPeriod(formatStartDate);

		await mdfRequestListPage.filterMDFRequestByPeriod(
			'2024-07-11',
			'2024-07-12'
		);

		await page.getByText('MDF Requests').click();

		await expect(endActPeriod).toBeVisible();
		await expect(startActPeriod).toBeVisible();

		await mdfRequestListPage.clearAllFilters();
		await mdfRequestListPage.filterButton.click();

		await mdfRequestListPage.activityAfterDateInput.fill('2024-08-09');
		await mdfRequestListPage.activityBeforeDateInput.fill('2024-08-10');

		await mdfRequestListPage.applyFilterButton.click();

		await page.getByText('MDF Requests').click();

		await expect(mdfRequestListPage.noEntriesFoundMessage).toBeVisible();
		await expect(endActPeriod).not.toBeVisible();
		await expect(startActPeriod).not.toBeVisible();
	});

	test('Filter data by Status', async ({mdfRequestListPage, page}) => {
		const autoGenerateData =
			await mdfRequestListPage.getGeneratedDataFromRequest(
				mdfRequest.overallCampaignName
			);
		const status = autoGenerateData.status;

		await mdfRequestListPage.filterMDFRequestByStatus(status);

		await mdfRequestListPage.mdfRequestHeading.click();

		await expect(status).toBeTruthy();

		await mdfRequestListPage.clearAllFilters();
		await mdfRequestListPage.filterButton.click();

		await page.getByLabel('Draft').check();

		await mdfRequestListPage.applyFilterButton.click();
		await mdfRequestListPage.mdfRequestHeading.click();

		await expect(mdfRequestListPage.noEntriesFoundMessage).toBeVisible();
	});

	test('Filter data by Partner', async ({mdfRequestListPage, page}) => {
		const partnerName = await mdfRequestListPage.getPartnerName(
			mdfRequest.companyName
		);

		await mdfRequestListPage.filterMDFRequestByPartner(
			mdfRequest.companyName
		);

		await page.getByText('MDF Requests').click();

		await expect(partnerName).toBeVisible();
	});

	test('Clean date filter fields when click on Clear All Filters', async ({
		mdfRequestListPage,
	}) => {
		await mdfRequestListPage.filterMDFRequestByPeriod(
			'2024-06-01',
			'2024-06-08'
		);

		await mdfRequestListPage.clearAllFilters();
		await mdfRequestListPage.filterButton.click();

		await expect(mdfRequestListPage.activityAfterDateInput).toBeEmpty();
		await expect(mdfRequestListPage.activityBeforeDateInput).toBeEmpty();
	});

	test('Download MDF Report', async ({mdfRequestListPage, page}) => {
		const downloadPromise = page.waitForEvent('download');
		await mdfRequestListPage.exportRequestButton.click();

		const downloadMDFReport = await downloadPromise;

		await downloadMDFReport.saveAs(
			'~/' + downloadMDFReport.suggestedFilename()
		);

		expect(downloadMDFReport.suggestedFilename()).toBe('MDF Requests.csv');
	});

	test('Change MDF Request Status', async ({
		mdfRequestFormPage,
		mdfRequestListPage,
	}) => {
		const autoGenerateData =
			await mdfRequestListPage.getGeneratedDataFromRequest(
				mdfRequest.overallCampaignName
			);
		const requestId = await mdfRequestListPage.getRequestId(
			autoGenerateData.requestId
		);

		await requestId.click();

		await mdfRequestFormPage.statusDropdown.click();
		await mdfRequestFormPage.statusDropDownOption('Approved');
		await mdfRequestFormPage.backButton.click();

		await expect(mdfRequestListPage.getStatus('Approved')).toBeTruthy();
	});

	test('Find a Request using the search input', async ({
		mdfRequestListPage,
	}) => {
		const campaignName = await mdfRequestListPage.getCampaignName();
		const cleanSearch = await mdfRequestListPage.cleanSearch;

		await mdfRequestListPage.filterUsingSearchInput('Test Campaign');

		await expect(campaignName).toBeVisible();

		await cleanSearch.click();
		await mdfRequestListPage.filterUsingSearchInput('Name');

		await expect(mdfRequestListPage.noEntriesFoundMessage).toBeVisible();
	});

	test('Complete A MDF Request through action button', async ({
		mdfRequestFormPage,
		mdfRequestListPage,
		page,
	}) => {
		const actionButton = await mdfRequestListPage.actionButton;
		const autoGenerateData =
			await mdfRequestListPage.getGeneratedDataFromRequest(
				mdfRequest.overallCampaignName
			);
		const completedTab = await mdfRequestListPage.completedTab;
		const completeMenuItem = await mdfRequestListPage.completeMenuItem;
		const requestId = await mdfRequestListPage.getRequestId(
			autoGenerateData.requestId
		);
		const successTooltip = await page.getByText(
			'Success:MDF Request successfully completed!'
		);

		await requestId.click();

		await mdfRequestFormPage.statusDropdown.click();
		await mdfRequestFormPage.statusDropDownOption('Approved');
		await mdfRequestFormPage.backButton.click();

		await page.once('dialog', async (dialog) => {
			expect(dialog.message()).toContain(
				'Are you sure you want to complete the MDF request?'
			);
			await dialog.accept();
		});

		await actionButton.click();
		await completeMenuItem.click();

		await expect(successTooltip).toBeVisible();

		await completedTab.click();

		await expect(requestId).toBeVisible();
	});
});
