##
## Test Suites
##

modified.files.includes[relevant][address-web-rule]=**

#
# Relevant
#

playwright.test.project[playwright-js-tomcat90-mysql57][relevant][address-web-rule]=address-web

relevant.rule.names=\
    address-web-rule

test.batch.names[relevant][address-web-rule]=\
    playwright-js-tomcat90-mysql57